### PR TITLE
feat: Add support for windows, backported from oHTGo/setup-cloudflare-warp-action

### PR DESCRIPTION
**Pull request by marcusramberg**
Tested on github managed `windows-latest` runner.

### CODE REVIEW

**Review by F21 — CHANGES_REQUESTED** [review]
Can you add windows to the test matrix for the tests?
- https://github.com/Boostport/setup-cloudflare-warp/blob/main/.github/workflows/tests.yml#L17
- https://github.com/Boostport/setup-cloudflare-warp/blob/main/.github/workflows/pull-requests.yml#L27

**Comment by marcusramberg** [comment]
> Can you add windows to the test matrix for the tests?
> 
> * https://github.com/Boostport/setup-cloudflare-warp/blob/main/.github/workflows/tests.yml#L17
> * https://github.com/Boostport/setup-cloudflare-warp/blob/main/.github/workflows/pull-requests.yml#L27

Yepp, I slightly started looking at that, wget isn't installed by default on windows runners tho, so I'd need a conditional for that test step I guess.

**Comment by marcusramberg** [comment]
Would you be ok with replacing it with `curl -I https://www.google.com/` ? That's available across win/linux/mac afaict.

**Comment by F21** [comment]
Sure! Let's do that!

**Review by F21 — APPROVED** [review]

**Comment by marcusramberg** [comment]
Thanks. <3

**Pull request merged**
